"""Texas State configuration (3rd state; first RED state).

Texas: 38 congressional districts (post-2020 census, gained 2), a bicameral
legislature with 150 State Representative ("House") districts and 31 State Senate
districts, and an OPEN primary (no party registration; voters choose a party ballot)
in March with a May majority-runoff if no candidate clears 50%.

County identifiers: Texas publishes results by county *name* (no 2-letter SoS code
system), so ``sos_code`` is the UPPER-cased county name, mirroring NY/ID. FIPS
suffixes are the 3-digit Census COUNTYFP within state FIPS 48. Generated from the
Census national county file by scripts/_gen_tx_config.py (254 counties).

Election data source: the Texas Legislative Council Capitol Data Portal
(data.capitol.texas.gov), via the ``tlc_capitol_tx`` adapter — canvass-grade
VTD-level returns (header County,FIPS,VTD,...,Office,Name,Party,Incumbent,Votes)
that roll up to clean county totals for all 254 counties every cycle 2016-2024
and carry an Incumbent Y/N flag. This replaced the community OpenElections-TX
precinct files, which had per-county mixed-granularity double-counting and only
101/254 counties for 2022. Fetch + place with scripts/download_tx_tlc.py.

Redistricting (revisit in PVI work): TX redrew all maps after the 2020 census
(used for 2022 + 2024), then enacted a 2025 mid-decade CONGRESSIONAL redraw that
applies to 2026 — the legislative (House/Senate) maps are UNCHANGED. So a single
``district_boundary_year`` can't capture the CD case: 2026 CONGRESSIONAL PVI needs
presidential results on the NEW 2025 boundaries; TLC already publishes a per-CD
2024 election report on the enacted 2025 plan (PLANC2333 r206), so no spatial join
is required. House/Senate stay on the stable post-2020 maps. VTD ids are NOT
comparable across redistricting vintages (the WA-2022 break) — aggregate to county
for any multi-cycle trend.
"""

from config.state_config import CountyInfo, StateConfig

# All 254 Texas counties. sos_code == UPPER county name. FIPS = 3-digit COUNTYFP
# within state FIPS 48. (Generated — see module docstring.)
_TX_COUNTIES = {
    'ANDERSON': CountyInfo('ANDERSON', '001', 'ANDERSON'),
    'ANDREWS': CountyInfo('ANDREWS', '003', 'ANDREWS'),
    'ANGELINA': CountyInfo('ANGELINA', '005', 'ANGELINA'),
    'ARANSAS': CountyInfo('ARANSAS', '007', 'ARANSAS'),
    'ARCHER': CountyInfo('ARCHER', '009', 'ARCHER'),
    'ARMSTRONG': CountyInfo('ARMSTRONG', '011', 'ARMSTRONG'),
    'ATASCOSA': CountyInfo('ATASCOSA', '013', 'ATASCOSA'),
    'AUSTIN': CountyInfo('AUSTIN', '015', 'AUSTIN'),
    'BAILEY': CountyInfo('BAILEY', '017', 'BAILEY'),
    'BANDERA': CountyInfo('BANDERA', '019', 'BANDERA'),
    'BASTROP': CountyInfo('BASTROP', '021', 'BASTROP'),
    'BAYLOR': CountyInfo('BAYLOR', '023', 'BAYLOR'),
    'BEE': CountyInfo('BEE', '025', 'BEE'),
    'BELL': CountyInfo('BELL', '027', 'BELL'),
    'BEXAR': CountyInfo('BEXAR', '029', 'BEXAR'),
    'BLANCO': CountyInfo('BLANCO', '031', 'BLANCO'),
    'BORDEN': CountyInfo('BORDEN', '033', 'BORDEN'),
    'BOSQUE': CountyInfo('BOSQUE', '035', 'BOSQUE'),
    'BOWIE': CountyInfo('BOWIE', '037', 'BOWIE'),
    'BRAZORIA': CountyInfo('BRAZORIA', '039', 'BRAZORIA'),
    'BRAZOS': CountyInfo('BRAZOS', '041', 'BRAZOS'),
    'BREWSTER': CountyInfo('BREWSTER', '043', 'BREWSTER'),
    'BRISCOE': CountyInfo('BRISCOE', '045', 'BRISCOE'),
    'BROOKS': CountyInfo('BROOKS', '047', 'BROOKS'),
    'BROWN': CountyInfo('BROWN', '049', 'BROWN'),
    'BURLESON': CountyInfo('BURLESON', '051', 'BURLESON'),
    'BURNET': CountyInfo('BURNET', '053', 'BURNET'),
    'CALDWELL': CountyInfo('CALDWELL', '055', 'CALDWELL'),
    'CALHOUN': CountyInfo('CALHOUN', '057', 'CALHOUN'),
    'CALLAHAN': CountyInfo('CALLAHAN', '059', 'CALLAHAN'),
    'CAMERON': CountyInfo('CAMERON', '061', 'CAMERON'),
    'CAMP': CountyInfo('CAMP', '063', 'CAMP'),
    'CARSON': CountyInfo('CARSON', '065', 'CARSON'),
    'CASS': CountyInfo('CASS', '067', 'CASS'),
    'CASTRO': CountyInfo('CASTRO', '069', 'CASTRO'),
    'CHAMBERS': CountyInfo('CHAMBERS', '071', 'CHAMBERS'),
    'CHEROKEE': CountyInfo('CHEROKEE', '073', 'CHEROKEE'),
    'CHILDRESS': CountyInfo('CHILDRESS', '075', 'CHILDRESS'),
    'CLAY': CountyInfo('CLAY', '077', 'CLAY'),
    'COCHRAN': CountyInfo('COCHRAN', '079', 'COCHRAN'),
    'COKE': CountyInfo('COKE', '081', 'COKE'),
    'COLEMAN': CountyInfo('COLEMAN', '083', 'COLEMAN'),
    'COLLIN': CountyInfo('COLLIN', '085', 'COLLIN'),
    'COLLINGSWORTH': CountyInfo('COLLINGSWORTH', '087', 'COLLINGSWORTH'),
    'COLORADO': CountyInfo('COLORADO', '089', 'COLORADO'),
    'COMAL': CountyInfo('COMAL', '091', 'COMAL'),
    'COMANCHE': CountyInfo('COMANCHE', '093', 'COMANCHE'),
    'CONCHO': CountyInfo('CONCHO', '095', 'CONCHO'),
    'COOKE': CountyInfo('COOKE', '097', 'COOKE'),
    'CORYELL': CountyInfo('CORYELL', '099', 'CORYELL'),
    'COTTLE': CountyInfo('COTTLE', '101', 'COTTLE'),
    'CRANE': CountyInfo('CRANE', '103', 'CRANE'),
    'CROCKETT': CountyInfo('CROCKETT', '105', 'CROCKETT'),
    'CROSBY': CountyInfo('CROSBY', '107', 'CROSBY'),
    'CULBERSON': CountyInfo('CULBERSON', '109', 'CULBERSON'),
    'DALLAM': CountyInfo('DALLAM', '111', 'DALLAM'),
    'DALLAS': CountyInfo('DALLAS', '113', 'DALLAS'),
    'DAWSON': CountyInfo('DAWSON', '115', 'DAWSON'),
    'DEAF SMITH': CountyInfo('DEAF SMITH', '117', 'DEAF SMITH'),
    'DELTA': CountyInfo('DELTA', '119', 'DELTA'),
    'DENTON': CountyInfo('DENTON', '121', 'DENTON'),
    'DEWITT': CountyInfo('DEWITT', '123', 'DEWITT'),
    'DICKENS': CountyInfo('DICKENS', '125', 'DICKENS'),
    'DIMMIT': CountyInfo('DIMMIT', '127', 'DIMMIT'),
    'DONLEY': CountyInfo('DONLEY', '129', 'DONLEY'),
    'DUVAL': CountyInfo('DUVAL', '131', 'DUVAL'),
    'EASTLAND': CountyInfo('EASTLAND', '133', 'EASTLAND'),
    'ECTOR': CountyInfo('ECTOR', '135', 'ECTOR'),
    'EDWARDS': CountyInfo('EDWARDS', '137', 'EDWARDS'),
    'EL PASO': CountyInfo('EL PASO', '141', 'EL PASO'),
    'ELLIS': CountyInfo('ELLIS', '139', 'ELLIS'),
    'ERATH': CountyInfo('ERATH', '143', 'ERATH'),
    'FALLS': CountyInfo('FALLS', '145', 'FALLS'),
    'FANNIN': CountyInfo('FANNIN', '147', 'FANNIN'),
    'FAYETTE': CountyInfo('FAYETTE', '149', 'FAYETTE'),
    'FISHER': CountyInfo('FISHER', '151', 'FISHER'),
    'FLOYD': CountyInfo('FLOYD', '153', 'FLOYD'),
    'FOARD': CountyInfo('FOARD', '155', 'FOARD'),
    'FORT BEND': CountyInfo('FORT BEND', '157', 'FORT BEND'),
    'FRANKLIN': CountyInfo('FRANKLIN', '159', 'FRANKLIN'),
    'FREESTONE': CountyInfo('FREESTONE', '161', 'FREESTONE'),
    'FRIO': CountyInfo('FRIO', '163', 'FRIO'),
    'GAINES': CountyInfo('GAINES', '165', 'GAINES'),
    'GALVESTON': CountyInfo('GALVESTON', '167', 'GALVESTON'),
    'GARZA': CountyInfo('GARZA', '169', 'GARZA'),
    'GILLESPIE': CountyInfo('GILLESPIE', '171', 'GILLESPIE'),
    'GLASSCOCK': CountyInfo('GLASSCOCK', '173', 'GLASSCOCK'),
    'GOLIAD': CountyInfo('GOLIAD', '175', 'GOLIAD'),
    'GONZALES': CountyInfo('GONZALES', '177', 'GONZALES'),
    'GRAY': CountyInfo('GRAY', '179', 'GRAY'),
    'GRAYSON': CountyInfo('GRAYSON', '181', 'GRAYSON'),
    'GREGG': CountyInfo('GREGG', '183', 'GREGG'),
    'GRIMES': CountyInfo('GRIMES', '185', 'GRIMES'),
    'GUADALUPE': CountyInfo('GUADALUPE', '187', 'GUADALUPE'),
    'HALE': CountyInfo('HALE', '189', 'HALE'),
    'HALL': CountyInfo('HALL', '191', 'HALL'),
    'HAMILTON': CountyInfo('HAMILTON', '193', 'HAMILTON'),
    'HANSFORD': CountyInfo('HANSFORD', '195', 'HANSFORD'),
    'HARDEMAN': CountyInfo('HARDEMAN', '197', 'HARDEMAN'),
    'HARDIN': CountyInfo('HARDIN', '199', 'HARDIN'),
    'HARRIS': CountyInfo('HARRIS', '201', 'HARRIS'),
    'HARRISON': CountyInfo('HARRISON', '203', 'HARRISON'),
    'HARTLEY': CountyInfo('HARTLEY', '205', 'HARTLEY'),
    'HASKELL': CountyInfo('HASKELL', '207', 'HASKELL'),
    'HAYS': CountyInfo('HAYS', '209', 'HAYS'),
    'HEMPHILL': CountyInfo('HEMPHILL', '211', 'HEMPHILL'),
    'HENDERSON': CountyInfo('HENDERSON', '213', 'HENDERSON'),
    'HIDALGO': CountyInfo('HIDALGO', '215', 'HIDALGO'),
    'HILL': CountyInfo('HILL', '217', 'HILL'),
    'HOCKLEY': CountyInfo('HOCKLEY', '219', 'HOCKLEY'),
    'HOOD': CountyInfo('HOOD', '221', 'HOOD'),
    'HOPKINS': CountyInfo('HOPKINS', '223', 'HOPKINS'),
    'HOUSTON': CountyInfo('HOUSTON', '225', 'HOUSTON'),
    'HOWARD': CountyInfo('HOWARD', '227', 'HOWARD'),
    'HUDSPETH': CountyInfo('HUDSPETH', '229', 'HUDSPETH'),
    'HUNT': CountyInfo('HUNT', '231', 'HUNT'),
    'HUTCHINSON': CountyInfo('HUTCHINSON', '233', 'HUTCHINSON'),
    'IRION': CountyInfo('IRION', '235', 'IRION'),
    'JACK': CountyInfo('JACK', '237', 'JACK'),
    'JACKSON': CountyInfo('JACKSON', '239', 'JACKSON'),
    'JASPER': CountyInfo('JASPER', '241', 'JASPER'),
    'JEFF DAVIS': CountyInfo('JEFF DAVIS', '243', 'JEFF DAVIS'),
    'JEFFERSON': CountyInfo('JEFFERSON', '245', 'JEFFERSON'),
    'JIM HOGG': CountyInfo('JIM HOGG', '247', 'JIM HOGG'),
    'JIM WELLS': CountyInfo('JIM WELLS', '249', 'JIM WELLS'),
    'JOHNSON': CountyInfo('JOHNSON', '251', 'JOHNSON'),
    'JONES': CountyInfo('JONES', '253', 'JONES'),
    'KARNES': CountyInfo('KARNES', '255', 'KARNES'),
    'KAUFMAN': CountyInfo('KAUFMAN', '257', 'KAUFMAN'),
    'KENDALL': CountyInfo('KENDALL', '259', 'KENDALL'),
    'KENEDY': CountyInfo('KENEDY', '261', 'KENEDY'),
    'KENT': CountyInfo('KENT', '263', 'KENT'),
    'KERR': CountyInfo('KERR', '265', 'KERR'),
    'KIMBLE': CountyInfo('KIMBLE', '267', 'KIMBLE'),
    'KING': CountyInfo('KING', '269', 'KING'),
    'KINNEY': CountyInfo('KINNEY', '271', 'KINNEY'),
    'KLEBERG': CountyInfo('KLEBERG', '273', 'KLEBERG'),
    'KNOX': CountyInfo('KNOX', '275', 'KNOX'),
    'LA SALLE': CountyInfo('LA SALLE', '283', 'LA SALLE'),
    'LAMAR': CountyInfo('LAMAR', '277', 'LAMAR'),
    'LAMB': CountyInfo('LAMB', '279', 'LAMB'),
    'LAMPASAS': CountyInfo('LAMPASAS', '281', 'LAMPASAS'),
    'LAVACA': CountyInfo('LAVACA', '285', 'LAVACA'),
    'LEE': CountyInfo('LEE', '287', 'LEE'),
    'LEON': CountyInfo('LEON', '289', 'LEON'),
    'LIBERTY': CountyInfo('LIBERTY', '291', 'LIBERTY'),
    'LIMESTONE': CountyInfo('LIMESTONE', '293', 'LIMESTONE'),
    'LIPSCOMB': CountyInfo('LIPSCOMB', '295', 'LIPSCOMB'),
    'LIVE OAK': CountyInfo('LIVE OAK', '297', 'LIVE OAK'),
    'LLANO': CountyInfo('LLANO', '299', 'LLANO'),
    'LOVING': CountyInfo('LOVING', '301', 'LOVING'),
    'LUBBOCK': CountyInfo('LUBBOCK', '303', 'LUBBOCK'),
    'LYNN': CountyInfo('LYNN', '305', 'LYNN'),
    'MADISON': CountyInfo('MADISON', '313', 'MADISON'),
    'MARION': CountyInfo('MARION', '315', 'MARION'),
    'MARTIN': CountyInfo('MARTIN', '317', 'MARTIN'),
    'MASON': CountyInfo('MASON', '319', 'MASON'),
    'MATAGORDA': CountyInfo('MATAGORDA', '321', 'MATAGORDA'),
    'MAVERICK': CountyInfo('MAVERICK', '323', 'MAVERICK'),
    'MCCULLOCH': CountyInfo('MCCULLOCH', '307', 'MCCULLOCH'),
    'MCLENNAN': CountyInfo('MCLENNAN', '309', 'MCLENNAN'),
    'MCMULLEN': CountyInfo('MCMULLEN', '311', 'MCMULLEN'),
    'MEDINA': CountyInfo('MEDINA', '325', 'MEDINA'),
    'MENARD': CountyInfo('MENARD', '327', 'MENARD'),
    'MIDLAND': CountyInfo('MIDLAND', '329', 'MIDLAND'),
    'MILAM': CountyInfo('MILAM', '331', 'MILAM'),
    'MILLS': CountyInfo('MILLS', '333', 'MILLS'),
    'MITCHELL': CountyInfo('MITCHELL', '335', 'MITCHELL'),
    'MONTAGUE': CountyInfo('MONTAGUE', '337', 'MONTAGUE'),
    'MONTGOMERY': CountyInfo('MONTGOMERY', '339', 'MONTGOMERY'),
    'MOORE': CountyInfo('MOORE', '341', 'MOORE'),
    'MORRIS': CountyInfo('MORRIS', '343', 'MORRIS'),
    'MOTLEY': CountyInfo('MOTLEY', '345', 'MOTLEY'),
    'NACOGDOCHES': CountyInfo('NACOGDOCHES', '347', 'NACOGDOCHES'),
    'NAVARRO': CountyInfo('NAVARRO', '349', 'NAVARRO'),
    'NEWTON': CountyInfo('NEWTON', '351', 'NEWTON'),
    'NOLAN': CountyInfo('NOLAN', '353', 'NOLAN'),
    'NUECES': CountyInfo('NUECES', '355', 'NUECES'),
    'OCHILTREE': CountyInfo('OCHILTREE', '357', 'OCHILTREE'),
    'OLDHAM': CountyInfo('OLDHAM', '359', 'OLDHAM'),
    'ORANGE': CountyInfo('ORANGE', '361', 'ORANGE'),
    'PALO PINTO': CountyInfo('PALO PINTO', '363', 'PALO PINTO'),
    'PANOLA': CountyInfo('PANOLA', '365', 'PANOLA'),
    'PARKER': CountyInfo('PARKER', '367', 'PARKER'),
    'PARMER': CountyInfo('PARMER', '369', 'PARMER'),
    'PECOS': CountyInfo('PECOS', '371', 'PECOS'),
    'POLK': CountyInfo('POLK', '373', 'POLK'),
    'POTTER': CountyInfo('POTTER', '375', 'POTTER'),
    'PRESIDIO': CountyInfo('PRESIDIO', '377', 'PRESIDIO'),
    'RAINS': CountyInfo('RAINS', '379', 'RAINS'),
    'RANDALL': CountyInfo('RANDALL', '381', 'RANDALL'),
    'REAGAN': CountyInfo('REAGAN', '383', 'REAGAN'),
    'REAL': CountyInfo('REAL', '385', 'REAL'),
    'RED RIVER': CountyInfo('RED RIVER', '387', 'RED RIVER'),
    'REEVES': CountyInfo('REEVES', '389', 'REEVES'),
    'REFUGIO': CountyInfo('REFUGIO', '391', 'REFUGIO'),
    'ROBERTS': CountyInfo('ROBERTS', '393', 'ROBERTS'),
    'ROBERTSON': CountyInfo('ROBERTSON', '395', 'ROBERTSON'),
    'ROCKWALL': CountyInfo('ROCKWALL', '397', 'ROCKWALL'),
    'RUNNELS': CountyInfo('RUNNELS', '399', 'RUNNELS'),
    'RUSK': CountyInfo('RUSK', '401', 'RUSK'),
    'SABINE': CountyInfo('SABINE', '403', 'SABINE'),
    'SAN AUGUSTINE': CountyInfo('SAN AUGUSTINE', '405', 'SAN AUGUSTINE'),
    'SAN JACINTO': CountyInfo('SAN JACINTO', '407', 'SAN JACINTO'),
    'SAN PATRICIO': CountyInfo('SAN PATRICIO', '409', 'SAN PATRICIO'),
    'SAN SABA': CountyInfo('SAN SABA', '411', 'SAN SABA'),
    'SCHLEICHER': CountyInfo('SCHLEICHER', '413', 'SCHLEICHER'),
    'SCURRY': CountyInfo('SCURRY', '415', 'SCURRY'),
    'SHACKELFORD': CountyInfo('SHACKELFORD', '417', 'SHACKELFORD'),
    'SHELBY': CountyInfo('SHELBY', '419', 'SHELBY'),
    'SHERMAN': CountyInfo('SHERMAN', '421', 'SHERMAN'),
    'SMITH': CountyInfo('SMITH', '423', 'SMITH'),
    'SOMERVELL': CountyInfo('SOMERVELL', '425', 'SOMERVELL'),
    'STARR': CountyInfo('STARR', '427', 'STARR'),
    'STEPHENS': CountyInfo('STEPHENS', '429', 'STEPHENS'),
    'STERLING': CountyInfo('STERLING', '431', 'STERLING'),
    'STONEWALL': CountyInfo('STONEWALL', '433', 'STONEWALL'),
    'SUTTON': CountyInfo('SUTTON', '435', 'SUTTON'),
    'SWISHER': CountyInfo('SWISHER', '437', 'SWISHER'),
    'TARRANT': CountyInfo('TARRANT', '439', 'TARRANT'),
    'TAYLOR': CountyInfo('TAYLOR', '441', 'TAYLOR'),
    'TERRELL': CountyInfo('TERRELL', '443', 'TERRELL'),
    'TERRY': CountyInfo('TERRY', '445', 'TERRY'),
    'THROCKMORTON': CountyInfo('THROCKMORTON', '447', 'THROCKMORTON'),
    'TITUS': CountyInfo('TITUS', '449', 'TITUS'),
    'TOM GREEN': CountyInfo('TOM GREEN', '451', 'TOM GREEN'),
    'TRAVIS': CountyInfo('TRAVIS', '453', 'TRAVIS'),
    'TRINITY': CountyInfo('TRINITY', '455', 'TRINITY'),
    'TYLER': CountyInfo('TYLER', '457', 'TYLER'),
    'UPSHUR': CountyInfo('UPSHUR', '459', 'UPSHUR'),
    'UPTON': CountyInfo('UPTON', '461', 'UPTON'),
    'UVALDE': CountyInfo('UVALDE', '463', 'UVALDE'),
    'VAL VERDE': CountyInfo('VAL VERDE', '465', 'VAL VERDE'),
    'VAN ZANDT': CountyInfo('VAN ZANDT', '467', 'VAN ZANDT'),
    'VICTORIA': CountyInfo('VICTORIA', '469', 'VICTORIA'),
    'WALKER': CountyInfo('WALKER', '471', 'WALKER'),
    'WALLER': CountyInfo('WALLER', '473', 'WALLER'),
    'WARD': CountyInfo('WARD', '475', 'WARD'),
    'WASHINGTON': CountyInfo('WASHINGTON', '477', 'WASHINGTON'),
    'WEBB': CountyInfo('WEBB', '479', 'WEBB'),
    'WHARTON': CountyInfo('WHARTON', '481', 'WHARTON'),
    'WHEELER': CountyInfo('WHEELER', '483', 'WHEELER'),
    'WICHITA': CountyInfo('WICHITA', '485', 'WICHITA'),
    'WILBARGER': CountyInfo('WILBARGER', '487', 'WILBARGER'),
    'WILLACY': CountyInfo('WILLACY', '489', 'WILLACY'),
    'WILLIAMSON': CountyInfo('WILLIAMSON', '491', 'WILLIAMSON'),
    'WILSON': CountyInfo('WILSON', '493', 'WILSON'),
    'WINKLER': CountyInfo('WINKLER', '495', 'WINKLER'),
    'WISE': CountyInfo('WISE', '497', 'WISE'),
    'WOOD': CountyInfo('WOOD', '499', 'WOOD'),
    'YOAKUM': CountyInfo('YOAKUM', '501', 'YOAKUM'),
    'YOUNG': CountyInfo('YOUNG', '503', 'YOUNG'),
    'ZAPATA': CountyInfo('ZAPATA', '505', 'ZAPATA'),
    'ZAVALA': CountyInfo('ZAVALA', '507', 'ZAVALA'),
}

TX_CONFIG = StateConfig(
    state_code="TX",
    state_name="Texas",
    state_fips="48",
    congressional_districts=38,
    # Bicameral: lower chamber = 150-seat House; upper = 31-seat Senate.
    legislative_districts=150,
    legislative_label="State Representative District",
    upper_chamber_districts=31,
    upper_chamber_label="State Senate District",
    # TX lower chamber = House -> "hd" profiles, race "HOUSE DISTRICT N"
    # (vs NY Assembly defaults). Upper = Senate ("sd") for both.
    lower_chamber_prefix="hd",
    lower_chamber_race_keyword="house",
    lower_chamber_name="House",
    primary_system="partisan_open",   # open primary; pick a party ballot; May runoff
    voting_method="mixed",            # in-person + early + limited absentee (NOT all-mail)
    primary_month=3,                  # March
    mail_turnout_bonus=0.0,
    counties=_TX_COUNTIES,
    # Precinct/VTD results: Texas Legislative Council Capitol Data Portal
    # (canvass-grade, all 254 counties, Incumbent flag). See tlc_capitol_tx adapter.
    sos_base_url="https://data.capitol.texas.gov/",
    sos_csv_format="tlc_capitol_tx",
    # TX Ethics Commission publishes bulk CSV campaign finance (documented record
    # layouts) — NOT a Socrata API. The TX finance adapter (Phase 1) handles bulk;
    # api_base/datasets are Socrata-shaped and left empty here.
    state_finance_enabled=True,
    state_finance_api_base="",
    state_finance_datasets={},
    default_district="cd23",          # perennial TX swing CD
    district_boundary_year=2022,
)
